server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://120.76.201.50:3306/harukaze?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.harukaze.front.entity
logging:
  level: debug
