server:
  port: 10001
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql:///costume?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.harukaze.costume.app.entity

